version: "3.7"

services:
  back:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: